---
title: "Untitled"
author: "Arnold, Neunhoeffer, Sternberg"
date: "6 8 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(rvest)
library(magrittr)
library(stringr)


```


```{r}

paste("https://www.bundesverfassungsgericht.de/SiteGlobals/Forms/Suche/Entscheidungensuche_Formular.html?gtp=5403124_list%253D",i,"&language_=de", sep = "")



```


```{r}

pages <- c(1:3) # there are 721 pages to scrape

# getting the links to the decisions
links <- c()
for (i in 1:length(pages)){
  message("Getting decision ", i)
  html <- read_html(paste("https://www.bundesverfassungsgericht.de/SiteGlobals/Forms/Suche/Entscheidungensuche_Formular.html?gtp=5403124_list%253D",i,"&language_=de", sep = ""))
  href <- html %>% html_nodes(".relevance100+a") %>% html_attr("href")
  links <- c(links, href)
  message("taking a break")
  Sys.sleep(2)
}

links


```



```{r}

# select the decisions' links
decisions <- links[grep("^SharedDocs/Entscheidungen/",links)] %>% strsplit(";") %>% sapply("[", 1)

# the links must look like this: https://www.bundesverfassungsgericht.de/SharedDocs/Entscheidungen/DE/2019/07/rs20190730_2bvr168514.html

#generate the correct link be adding the necessary prefix to it:

decisions <- gsub("SharedDocs/", "https://www.bundesverfassungsgericht.de/SharedDocs/", decisions)

```


```{r}


# Testing for one text
case <- read_html("https://www.bundesverfassungsgericht.de/SharedDocs/Entscheidungen/DE/2019/05/qk20190524_1bvq004619.html")

header <- case %>% html_nodes("#navBreadcrumbs strong") %>% html_text()
cite <- case %>% html_nodes(".cite") %>% html_text()
chamber_senate <- case %>% html_nodes(".rr1") %>% html_text()

judge1 <- case %>% html_nodes(".absatz:nth-child(8) span") %>% html_text()
judge2 <- case %>% html_nodes(".absatz:nth-child(9) span") %>% html_text()
judge3 <- case %>% html_nodes(".absatz:nth-child(10) span") %>% html_text()

link_decision <- case %>% html_nodes(".cite a") %>% html_text()

aktenzeichen <- case %>% html_nodes(".az2 span") %>% html_text()


```

Looping over all decision links:


http://www.residualthoughts.com/2018/03/28/topic-analysis-of-tim-ferris-podcast-using-rvest/
```{r}

df_list <- list()

for(i in 1:length(decisions)){
  
  message("Scraping decision ", i)
  
  case <- read_html(decisions[i])

header <- case %>% html_nodes("#navBreadcrumbs strong") %>% html_text()
cite <- case %>% html_nodes(".cite") %>% html_text()
chamber_senate <- case %>% html_nodes(".rr1") %>% html_text()

judges_names <- case %>% html_nodes(".rr2 span") %>% html_text()
judge1 <- judges_names[1]
judge2 <- judges_names[2]
judge3 <- judges_names[3]

link_decision <- case %>% html_nodes(".cite a") %>% html_text()

aktenzeichen <- case %>% html_nodes(".az2 span") %>% html_text()

df_list[[i]] <-   data.frame(header = header, cite = cite, chamber_senate = chamber_senate,
                            judge1 = judge1, judge2 = judge2, judge3 = judge3,
                            link_decision = link_decision, aktenzeichen = aktenzeichen)

message("Iteration ", i, " of ", length(decisions),  " successful.")
message("taking a break")
Sys.sleep(5)
  
}

df_all_decisions  <- do.call("rbind", df_list)

save(df_all_decisions, file = "df_all_decisions.Rda")

```

## Data Cleaning

Clean the decisions. First drop the decisions with an "Urteil", because these are not Chamber decisions

```{r}
source("helper_functions.R")

#load the 

chamber_decisions <- df_all_decisions[!grepl("Urteil", df_all_decisions$header), ]


#some of the remaining ones are a "Beschluss", but also not a chamber decisions. Because we know that sometimes there is a mistake in the citings, we make double sure that we do not drop the wrong decisions by checking whether the word "Kammer" is in the header of the decision and the suggested citation:

chamber_decisions$check_if_chamber1 <- grepl("Kammer", chamber_decisions$cite)
chamber_decisions$check_if_chamber2 <- grepl("Kammer", as.character(chamber_decisions$chamber_senate))

#always true
chamber_decisions$check_if_chamber1 == chamber_decisions$check_if_chamber2

#only keep the decisions which are not chamber decisions

chamber_decisions <- chamber_decisions[chamber_decisions$check_if_chamber1 == TRUE, ]

#clean the aktenzeichen
chamber_decisions$az <- gsub("-", "",chamber_decisions$aktenzeichen) %>% str_trim()

#create date

for(i in 1:nrow(chamber_decisions)){
  
tmp <-  strsplit(as.character(chamber_decisions$header[i]), " ") %>%  unlist()
chamber_decisions$date[i] <- str_c(tmp[3:5], collapse = " ")

}

chamber_decisions$date <- german_date_to_date(chamber_decisions$date)

#extract the senate the chamber decision was decided in

chamber_decisions$senat <- str_extract(chamber_decisions$az, "[0-9]+") 
chamber_decisions$senat_check <- ifelse(grepl("Ersten Senats", as.character(chamber_decisions$chamber_senate)), 1, 2)


#extract the chambers

chamber_decisions$kammer_cit <- str_extract(as.character(chamber_decisions$cite), "[0-9]+")
chamber_decisions$kammer_txt <- str_extract(as.character(chamber_decisions$chamber_senate), "[0-9]+") 

#check:
chamber_decisions$kammer_cit == chamber_decisions$kammer_txt
  

#extracting the judges names

chamber_decisions$richter_txt <- 
chamber_decisions


#Einstweilige Anordnung:

chamber_decisions$anordnung <- ifelse(grepl("BvQ", chamber_decisions$az), 1, 0)



```


Bring them in the correct format:

```{r}

setwd("~/Dropbox/Papers Mannheim/Paper 2 Kammerbesetzung/Causal Inference Paper/chamber_paper_august2019/chamberGFCC")
case <- read.table("in/data-input/judicialData_Sep16.txt", sep="\t", encoding = "UTF-8")
names(case) <- c("i", "az", "date", "senat", "kammer_cit", "kammer_txt", "richter_raw", "richter_txt", "richter_cit", "Anordnung", "link")

```


```{r}



```






